"""initial schema

Revision ID: a2cb448fcbcf
Revises:
Create Date: 2026-08-28 23:21:05.787062

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a2cb448fcbcf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("openalex_id", sa.String(length=64), nullable=False),
        sa.Column("ror_id", sa.String(length=64), nullable=True),
        sa.Column("name_en", sa.String(length=512), nullable=False),
        sa.Column("name_ru", sa.String(length=512), nullable=True),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_institutions_openalex_id"), "institutions", ["openalex_id"], unique=True
    )
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("openalex_id", sa.String(length=64), nullable=False),
        sa.Column("orcid", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=512), nullable=False),
        sa.Column("last_known_institution_id", sa.Integer(), nullable=True),
        sa.Column("works_count", sa.Integer(), nullable=False),
        sa.Column("cited_by_count", sa.Integer(), nullable=False),
        sa.Column("h_index", sa.Integer(), nullable=True),
        sa.Column("i10_index", sa.Integer(), nullable=True),
        sa.Column("is_supervisor_candidate", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_known_institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_authors_is_supervisor_candidate"),
        "authors",
        ["is_supervisor_candidate"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authors_last_known_institution_id"),
        "authors",
        ["last_known_institution_id"],
        unique=False,
    )
    op.create_index(op.f("ix_authors_openalex_id"), "authors", ["openalex_id"], unique=True)
    op.create_table(
        "author_topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("topic_name", sa.String(length=512), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_author_topics_author_id"), "author_topics", ["author_id"], unique=False
    )
    op.create_table(
        "supervisor_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=True),
        sa.Column("profile_text", sa.Text(), nullable=False),
        sa.Column("n_works", sa.Integer(), nullable=False),
        sa.Column("n_abstracts", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supervisor_profiles_author_id"), "supervisor_profiles", ["author_id"], unique=True
    )
    op.create_table(
        "works",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("openalex_id", sa.String(length=64), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("abstract_text", sa.Text(), nullable=True),
        sa.Column("topics", sa.JSON(), nullable=True),
        sa.Column("cited_by_count", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("is_recent", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_works_author_id"), "works", ["author_id"], unique=False)
    op.create_index(op.f("ix_works_openalex_id"), "works", ["openalex_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_works_openalex_id"), table_name="works")
    op.drop_index(op.f("ix_works_author_id"), table_name="works")
    op.drop_table("works")
    op.drop_index(op.f("ix_supervisor_profiles_author_id"), table_name="supervisor_profiles")
    op.drop_table("supervisor_profiles")
    op.drop_index(op.f("ix_author_topics_author_id"), table_name="author_topics")
    op.drop_table("author_topics")
    op.drop_index(op.f("ix_authors_openalex_id"), table_name="authors")
    op.drop_index(op.f("ix_authors_last_known_institution_id"), table_name="authors")
    op.drop_index(op.f("ix_authors_is_supervisor_candidate"), table_name="authors")
    op.drop_table("authors")
    op.drop_index(op.f("ix_institutions_openalex_id"), table_name="institutions")
    op.drop_table("institutions")
    # ### end Alembic commands ###
